# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remapper.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 400)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_Keyboard = QtWidgets.QGroupBox(Form)
        self.groupBox_Keyboard.setObjectName("groupBox_Keyboard")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_Keyboard)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_1 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_1.setText("")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 4, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 0, 5, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 6, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 0, 7, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 1, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 1, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 1, 2, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 1, 3, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 1, 4, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 1, 5, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 1, 6, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 1, 7, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 2, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 2, 1, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 2, 2, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 2, 3, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_21.setText("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_21, 2, 4, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout.addWidget(self.pushButton_22, 2, 5, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_23.setText("")
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout.addWidget(self.pushButton_23, 2, 6, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_24.setText("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.pushButton_24, 2, 7, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_25.setText("")
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout.addWidget(self.pushButton_25, 3, 0, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_26.setText("")
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout.addWidget(self.pushButton_26, 3, 1, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_27.setText("")
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout.addWidget(self.pushButton_27, 3, 2, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_28.setText("")
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout.addWidget(self.pushButton_28, 3, 3, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_29.setText("")
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout.addWidget(self.pushButton_29, 3, 4, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_30.setText("")
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout.addWidget(self.pushButton_30, 3, 5, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_31.setText("")
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout.addWidget(self.pushButton_31, 3, 6, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_32.setText("")
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout.addWidget(self.pushButton_32, 3, 7, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_33.setText("")
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout.addWidget(self.pushButton_33, 4, 0, 1, 1)
        self.pushButton_34 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_34.setText("")
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayout.addWidget(self.pushButton_34, 4, 1, 1, 1)
        self.pushButton_35 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_35.setText("")
        self.pushButton_35.setObjectName("pushButton_35")
        self.gridLayout.addWidget(self.pushButton_35, 4, 2, 1, 1)
        self.pushButton_36 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_36.setText("")
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout.addWidget(self.pushButton_36, 4, 3, 1, 1)
        self.pushButton_37 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_37.setText("")
        self.pushButton_37.setObjectName("pushButton_37")
        self.gridLayout.addWidget(self.pushButton_37, 4, 4, 1, 1)
        self.pushButton_38 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_38.setText("")
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout.addWidget(self.pushButton_38, 4, 5, 1, 1)
        self.pushButton_39 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_39.setText("")
        self.pushButton_39.setObjectName("pushButton_39")
        self.gridLayout.addWidget(self.pushButton_39, 4, 6, 1, 1)
        self.pushButton_40 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_40.setText("")
        self.pushButton_40.setObjectName("pushButton_40")
        self.gridLayout.addWidget(self.pushButton_40, 4, 7, 1, 1)
        self.pushButton_41 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_41.setText("")
        self.pushButton_41.setObjectName("pushButton_41")
        self.gridLayout.addWidget(self.pushButton_41, 5, 0, 1, 1)
        self.pushButton_42 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_42.setText("")
        self.pushButton_42.setObjectName("pushButton_42")
        self.gridLayout.addWidget(self.pushButton_42, 5, 1, 1, 1)
        self.pushButton_43 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_43.setText("")
        self.pushButton_43.setObjectName("pushButton_43")
        self.gridLayout.addWidget(self.pushButton_43, 5, 2, 1, 1)
        self.pushButton_44 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_44.setText("")
        self.pushButton_44.setObjectName("pushButton_44")
        self.gridLayout.addWidget(self.pushButton_44, 5, 3, 1, 1)
        self.pushButton_45 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_45.setText("")
        self.pushButton_45.setObjectName("pushButton_45")
        self.gridLayout.addWidget(self.pushButton_45, 5, 4, 1, 1)
        self.pushButton_46 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_46.setText("")
        self.pushButton_46.setObjectName("pushButton_46")
        self.gridLayout.addWidget(self.pushButton_46, 5, 5, 1, 1)
        self.pushButton_47 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_47.setText("")
        self.pushButton_47.setObjectName("pushButton_47")
        self.gridLayout.addWidget(self.pushButton_47, 5, 6, 1, 1)
        self.pushButton_48 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_48.setText("")
        self.pushButton_48.setObjectName("pushButton_48")
        self.gridLayout.addWidget(self.pushButton_48, 5, 7, 1, 1)
        self.pushButton_49 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_49.setText("")
        self.pushButton_49.setObjectName("pushButton_49")
        self.gridLayout.addWidget(self.pushButton_49, 6, 0, 1, 1)
        self.pushButton_50 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_50.setText("")
        self.pushButton_50.setObjectName("pushButton_50")
        self.gridLayout.addWidget(self.pushButton_50, 6, 1, 1, 1)
        self.pushButton_51 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_51.setText("")
        self.pushButton_51.setObjectName("pushButton_51")
        self.gridLayout.addWidget(self.pushButton_51, 6, 2, 1, 1)
        self.pushButton_52 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_52.setText("")
        self.pushButton_52.setObjectName("pushButton_52")
        self.gridLayout.addWidget(self.pushButton_52, 6, 3, 1, 1)
        self.pushButton_53 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_53.setText("")
        self.pushButton_53.setObjectName("pushButton_53")
        self.gridLayout.addWidget(self.pushButton_53, 6, 4, 1, 1)
        self.pushButton_54 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_54.setText("")
        self.pushButton_54.setObjectName("pushButton_54")
        self.gridLayout.addWidget(self.pushButton_54, 6, 5, 1, 1)
        self.pushButton_55 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_55.setText("")
        self.pushButton_55.setObjectName("pushButton_55")
        self.gridLayout.addWidget(self.pushButton_55, 6, 6, 1, 1)
        self.pushButton_56 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_56.setText("")
        self.pushButton_56.setObjectName("pushButton_56")
        self.gridLayout.addWidget(self.pushButton_56, 6, 7, 1, 1)
        self.pushButton_57 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_57.setText("")
        self.pushButton_57.setObjectName("pushButton_57")
        self.gridLayout.addWidget(self.pushButton_57, 7, 0, 1, 1)
        self.pushButton_58 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_58.setText("")
        self.pushButton_58.setObjectName("pushButton_58")
        self.gridLayout.addWidget(self.pushButton_58, 7, 1, 1, 1)
        self.pushButton_59 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_59.setText("")
        self.pushButton_59.setObjectName("pushButton_59")
        self.gridLayout.addWidget(self.pushButton_59, 7, 2, 1, 1)
        self.pushButton_60 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_60.setText("")
        self.pushButton_60.setObjectName("pushButton_60")
        self.gridLayout.addWidget(self.pushButton_60, 7, 3, 1, 1)
        self.pushButton_61 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_61.setText("")
        self.pushButton_61.setObjectName("pushButton_61")
        self.gridLayout.addWidget(self.pushButton_61, 7, 4, 1, 1)
        self.pushButton_62 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_62.setText("")
        self.pushButton_62.setObjectName("pushButton_62")
        self.gridLayout.addWidget(self.pushButton_62, 7, 5, 1, 1)
        self.pushButton_63 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_63.setText("")
        self.pushButton_63.setObjectName("pushButton_63")
        self.gridLayout.addWidget(self.pushButton_63, 7, 6, 1, 1)
        self.pushButton_64 = QtWidgets.QPushButton(self.groupBox_Keyboard)
        self.pushButton_64.setText("")
        self.pushButton_64.setObjectName("pushButton_64")
        self.gridLayout.addWidget(self.pushButton_64, 7, 7, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_Keyboard)
        self.groupBox_Remapping = QtWidgets.QGroupBox(Form)
        self.groupBox_Remapping.setObjectName("groupBox_Remapping")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_Remapping)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_KeyNumber = QtWidgets.QLabel(self.groupBox_Remapping)
        self.label_KeyNumber.setObjectName("label_KeyNumber")
        self.gridLayout_2.addWidget(self.label_KeyNumber, 0, 0, 1, 1)
        self.lineEdit_KeyNumber = QtWidgets.QLineEdit(self.groupBox_Remapping)
        self.lineEdit_KeyNumber.setObjectName("lineEdit_KeyNumber")
        self.gridLayout_2.addWidget(self.lineEdit_KeyNumber, 0, 1, 1, 1)
        self.label_KeyCode = QtWidgets.QLabel(self.groupBox_Remapping)
        self.label_KeyCode.setObjectName("label_KeyCode")
        self.gridLayout_2.addWidget(self.label_KeyCode, 1, 0, 1, 1)
        self.lineEdit_KeyCode = QtWidgets.QLineEdit(self.groupBox_Remapping)
        self.lineEdit_KeyCode.setObjectName("lineEdit_KeyCode")
        self.gridLayout_2.addWidget(self.lineEdit_KeyCode, 1, 1, 1, 1)
        self.pushButton_SetUp = QtWidgets.QPushButton(self.groupBox_Remapping)
        self.pushButton_SetUp.setObjectName("pushButton_SetUp")
        self.gridLayout_2.addWidget(self.pushButton_SetUp, 2, 0, 1, 2)
        self.horizontalLayout.addWidget(self.groupBox_Remapping)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_Keyboard.setTitle(_translate("Form", "Keyboard(8X8)"))
        self.groupBox_Remapping.setTitle(_translate("Form", "Remapping"))
        self.label_KeyNumber.setText(_translate("Form", "keynumber"))
        self.label_KeyCode.setText(_translate("Form", "keycode"))
        self.pushButton_SetUp.setText(_translate("Form", "set up"))
