# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sub_ui_bluetooth.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Subui_BlueTooth(object):
    def setupUi(self, Subui_BlueTooth):
        Subui_BlueTooth.setObjectName("Subui_BlueTooth")
        Subui_BlueTooth.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Subui_BlueTooth)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_RS = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_RS.setObjectName("groupBox_RS")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_RS)
        self.gridLayout.setObjectName("gridLayout")
        self.label_RECIEVE = QtWidgets.QLabel(self.groupBox_RS)
        self.label_RECIEVE.setObjectName("label_RECIEVE")
        self.gridLayout.addWidget(self.label_RECIEVE, 0, 0, 1, 1)
        self.label_SEND = QtWidgets.QLabel(self.groupBox_RS)
        self.label_SEND.setObjectName("label_SEND")
        self.gridLayout.addWidget(self.label_SEND, 0, 1, 1, 1)
        self.textBrowser_RECEIVE = QtWidgets.QTextBrowser(self.groupBox_RS)
        self.textBrowser_RECEIVE.setObjectName("textBrowser_RECEIVE")
        self.gridLayout.addWidget(self.textBrowser_RECEIVE, 1, 0, 1, 1)
        self.textBrowser_SEND = QtWidgets.QTextBrowser(self.groupBox_RS)
        self.textBrowser_SEND.setObjectName("textBrowser_SEND")
        self.gridLayout.addWidget(self.textBrowser_SEND, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_RS, 1, 0, 1, 2)
        self.groupBox_Operate = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Operate.setObjectName("groupBox_Operate")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_Operate)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_FindDevices = QtWidgets.QPushButton(self.groupBox_Operate)
        self.pushButton_FindDevices.setObjectName("pushButton_FindDevices")
        self.verticalLayout.addWidget(self.pushButton_FindDevices)
        self.pushButton_ConnectDevice = QtWidgets.QPushButton(self.groupBox_Operate)
        self.pushButton_ConnectDevice.setObjectName("pushButton_ConnectDevice")
        self.verticalLayout.addWidget(self.pushButton_ConnectDevice)
        self.pushButton_ReadConfig = QtWidgets.QPushButton(self.groupBox_Operate)
        self.pushButton_ReadConfig.setObjectName("pushButton_ReadConfig")
        self.verticalLayout.addWidget(self.pushButton_ReadConfig)
        self.pushButton_SendData = QtWidgets.QPushButton(self.groupBox_Operate)
        self.pushButton_SendData.setObjectName("pushButton_SendData")
        self.verticalLayout.addWidget(self.pushButton_SendData)
        self.pushButton_ReceiveData = QtWidgets.QPushButton(self.groupBox_Operate)
        self.pushButton_ReceiveData.setObjectName("pushButton_ReceiveData")
        self.verticalLayout.addWidget(self.pushButton_ReceiveData)
        self.pushButton_Clear = QtWidgets.QPushButton(self.groupBox_Operate)
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.verticalLayout.addWidget(self.pushButton_Clear)
        self.gridLayout_5.addWidget(self.groupBox_Operate, 0, 2, 2, 1)
        self.groupBox_Device = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Device.setObjectName("groupBox_Device")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_Device)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_Addr = QtWidgets.QLabel(self.groupBox_Device)
        self.label_Addr.setObjectName("label_Addr")
        self.horizontalLayout.addWidget(self.label_Addr)
        self.lineEdit_Address = QtWidgets.QLineEdit(self.groupBox_Device)
        self.lineEdit_Address.setObjectName("lineEdit_Address")
        self.horizontalLayout.addWidget(self.lineEdit_Address)
        self.gridLayout_5.addWidget(self.groupBox_Device, 0, 0, 1, 1)
        Subui_BlueTooth.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Subui_BlueTooth)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        self.menuSet = QtWidgets.QMenu(self.menubar)
        self.menuSet.setObjectName("menuSet")
        self.menuSettings = QtWidgets.QMenu(self.menuSet)
        self.menuSettings.setObjectName("menuSettings")
        Subui_BlueTooth.setMenuBar(self.menubar)
        self.actionFonts = QtWidgets.QAction(Subui_BlueTooth)
        self.actionFonts.setObjectName("actionFonts")
        self.actionQuit = QtWidgets.QAction(Subui_BlueTooth)
        self.actionQuit.setObjectName("actionQuit")
        self.menuSettings.addAction(self.actionFonts)
        self.menuSet.addAction(self.menuSettings.menuAction())
        self.menuSet.addSeparator()
        self.menuSet.addAction(self.actionQuit)
        self.menubar.addAction(self.menuSet.menuAction())

        self.retranslateUi(Subui_BlueTooth)
        QtCore.QMetaObject.connectSlotsByName(Subui_BlueTooth)

    def retranslateUi(self, Subui_BlueTooth):
        _translate = QtCore.QCoreApplication.translate
        Subui_BlueTooth.setWindowTitle(_translate("Subui_BlueTooth", "BlueTooth"))
        self.groupBox_RS.setTitle(_translate("Subui_BlueTooth", "Receive and Send "))
        self.label_RECIEVE.setText(_translate("Subui_BlueTooth", "RECEIVE"))
        self.label_SEND.setText(_translate("Subui_BlueTooth", "SEND"))
        self.groupBox_Operate.setTitle(_translate("Subui_BlueTooth", "Operate"))
        self.pushButton_FindDevices.setText(_translate("Subui_BlueTooth", "Find devices"))
        self.pushButton_ConnectDevice.setText(_translate("Subui_BlueTooth", "Connect device"))
        self.pushButton_ReadConfig.setText(_translate("Subui_BlueTooth", "Read config"))
        self.pushButton_SendData.setText(_translate("Subui_BlueTooth", "Send data"))
        self.pushButton_ReceiveData.setText(_translate("Subui_BlueTooth", "Receive data"))
        self.pushButton_Clear.setText(_translate("Subui_BlueTooth", "Clear history"))
        self.groupBox_Device.setTitle(_translate("Subui_BlueTooth", "Device"))
        self.label_Addr.setText(_translate("Subui_BlueTooth", "Address"))
        self.menuSet.setTitle(_translate("Subui_BlueTooth", "System"))
        self.menuSettings.setTitle(_translate("Subui_BlueTooth", "Settings"))
        self.actionFonts.setText(_translate("Subui_BlueTooth", "Fonts"))
        self.actionQuit.setText(_translate("Subui_BlueTooth", "Quit"))
