# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sub_ui_i2c.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Subui_I2C(object):
    def setupUi(self, Subui_I2C):
        Subui_I2C.setObjectName("Subui_I2C")
        Subui_I2C.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Subui_I2C)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_Device = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Device.setObjectName("groupBox_Device")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_Device)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_VID = QtWidgets.QLabel(self.groupBox_Device)
        self.label_VID.setObjectName("label_VID")
        self.horizontalLayout.addWidget(self.label_VID)
        self.lineEdit_VID = QtWidgets.QLineEdit(self.groupBox_Device)
        self.lineEdit_VID.setObjectName("lineEdit_VID")
        self.horizontalLayout.addWidget(self.lineEdit_VID)
        self.label_PID = QtWidgets.QLabel(self.groupBox_Device)
        self.label_PID.setObjectName("label_PID")
        self.horizontalLayout.addWidget(self.label_PID)
        self.lineEdit_PID = QtWidgets.QLineEdit(self.groupBox_Device)
        self.lineEdit_PID.setObjectName("lineEdit_PID")
        self.horizontalLayout.addWidget(self.lineEdit_PID)
        self.label_Interface = QtWidgets.QLabel(self.groupBox_Device)
        self.label_Interface.setObjectName("label_Interface")
        self.horizontalLayout.addWidget(self.label_Interface)
        self.lineEdit_Interface = QtWidgets.QLineEdit(self.groupBox_Device)
        self.lineEdit_Interface.setObjectName("lineEdit_Interface")
        self.horizontalLayout.addWidget(self.lineEdit_Interface)
        self.gridLayout_5.addWidget(self.groupBox_Device, 0, 0, 1, 2)
        self.groupBox_EPI = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_EPI.setObjectName("groupBox_EPI")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_EPI)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_EPIAddress = QtWidgets.QLineEdit(self.groupBox_EPI)
        self.lineEdit_EPIAddress.setObjectName("lineEdit_EPIAddress")
        self.gridLayout_2.addWidget(self.lineEdit_EPIAddress, 0, 1, 1, 1)
        self.lineEdit_EPILength = QtWidgets.QLineEdit(self.groupBox_EPI)
        self.lineEdit_EPILength.setObjectName("lineEdit_EPILength")
        self.gridLayout_2.addWidget(self.lineEdit_EPILength, 2, 1, 1, 1)
        self.label_EPIAddress = QtWidgets.QLabel(self.groupBox_EPI)
        self.label_EPIAddress.setObjectName("label_EPIAddress")
        self.gridLayout_2.addWidget(self.label_EPIAddress, 0, 0, 1, 1)
        self.label_EPIClass = QtWidgets.QLabel(self.groupBox_EPI)
        self.label_EPIClass.setObjectName("label_EPIClass")
        self.gridLayout_2.addWidget(self.label_EPIClass, 1, 0, 1, 1)
        self.lineEdit_EPIClass = QtWidgets.QLineEdit(self.groupBox_EPI)
        self.lineEdit_EPIClass.setObjectName("lineEdit_EPIClass")
        self.gridLayout_2.addWidget(self.lineEdit_EPIClass, 1, 1, 1, 1)
        self.label_EPILength = QtWidgets.QLabel(self.groupBox_EPI)
        self.label_EPILength.setObjectName("label_EPILength")
        self.gridLayout_2.addWidget(self.label_EPILength, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_EPI, 1, 0, 1, 1)
        self.groupBox_RS = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_RS.setObjectName("groupBox_RS")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_RS)
        self.gridLayout.setObjectName("gridLayout")
        self.label_RECIEVE = QtWidgets.QLabel(self.groupBox_RS)
        self.label_RECIEVE.setObjectName("label_RECIEVE")
        self.gridLayout.addWidget(self.label_RECIEVE, 0, 0, 1, 1)
        self.label_SEND = QtWidgets.QLabel(self.groupBox_RS)
        self.label_SEND.setObjectName("label_SEND")
        self.gridLayout.addWidget(self.label_SEND, 0, 1, 1, 1)
        self.lineEdit_RECEIVE = QtWidgets.QLineEdit(self.groupBox_RS)
        self.lineEdit_RECEIVE.setObjectName("lineEdit_RECEIVE")
        self.gridLayout.addWidget(self.lineEdit_RECEIVE, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_RS)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.lineEdit_SEND_1 = QtWidgets.QLineEdit(self.groupBox_RS)
        self.lineEdit_SEND_1.setObjectName("lineEdit_SEND_1")
        self.gridLayout.addWidget(self.lineEdit_SEND_1, 1, 2, 1, 1)
        self.textBrowser_RECEIVE = QtWidgets.QTextBrowser(self.groupBox_RS)
        self.textBrowser_RECEIVE.setObjectName("textBrowser_RECEIVE")
        self.gridLayout.addWidget(self.textBrowser_RECEIVE, 2, 0, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_RS)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.lineEdit_SEND_2 = QtWidgets.QLineEdit(self.groupBox_RS)
        self.lineEdit_SEND_2.setObjectName("lineEdit_SEND_2")
        self.gridLayout.addWidget(self.lineEdit_SEND_2, 2, 2, 1, 1)
        self.textBrowser_SEND = QtWidgets.QTextBrowser(self.groupBox_RS)
        self.textBrowser_SEND.setObjectName("textBrowser_SEND")
        self.gridLayout.addWidget(self.textBrowser_SEND, 3, 1, 1, 2)
        self.gridLayout_5.addWidget(self.groupBox_RS, 2, 0, 1, 2)
        self.groupBox_Operate = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Operate.setObjectName("groupBox_Operate")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_Operate)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_FindDevices = QtWidgets.QPushButton(self.groupBox_Operate)
        self.pushButton_FindDevices.setObjectName("pushButton_FindDevices")
        self.verticalLayout.addWidget(self.pushButton_FindDevices)
        self.pushButton_ConnectDevice = QtWidgets.QPushButton(self.groupBox_Operate)
        self.pushButton_ConnectDevice.setObjectName("pushButton_ConnectDevice")
        self.verticalLayout.addWidget(self.pushButton_ConnectDevice)
        self.pushButton_ReadConfig = QtWidgets.QPushButton(self.groupBox_Operate)
        self.pushButton_ReadConfig.setObjectName("pushButton_ReadConfig")
        self.verticalLayout.addWidget(self.pushButton_ReadConfig)
        self.pushButton_SendData = QtWidgets.QPushButton(self.groupBox_Operate)
        self.pushButton_SendData.setObjectName("pushButton_SendData")
        self.verticalLayout.addWidget(self.pushButton_SendData)
        self.pushButton_ReceiveData = QtWidgets.QPushButton(self.groupBox_Operate)
        self.pushButton_ReceiveData.setObjectName("pushButton_ReceiveData")
        self.verticalLayout.addWidget(self.pushButton_ReceiveData)
        self.pushButton_Clear = QtWidgets.QPushButton(self.groupBox_Operate)
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.verticalLayout.addWidget(self.pushButton_Clear)
        self.gridLayout_5.addWidget(self.groupBox_Operate, 0, 2, 3, 1)
        self.groupBox_EPO = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_EPO.setObjectName("groupBox_EPO")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_EPO)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_EPOAddress = QtWidgets.QLineEdit(self.groupBox_EPO)
        self.lineEdit_EPOAddress.setObjectName("lineEdit_EPOAddress")
        self.gridLayout_4.addWidget(self.lineEdit_EPOAddress, 0, 1, 1, 1)
        self.label_EPOLength = QtWidgets.QLabel(self.groupBox_EPO)
        self.label_EPOLength.setObjectName("label_EPOLength")
        self.gridLayout_4.addWidget(self.label_EPOLength, 2, 0, 1, 1)
        self.label_EPOAddress = QtWidgets.QLabel(self.groupBox_EPO)
        self.label_EPOAddress.setObjectName("label_EPOAddress")
        self.gridLayout_4.addWidget(self.label_EPOAddress, 0, 0, 1, 1)
        self.label_EPOClass = QtWidgets.QLabel(self.groupBox_EPO)
        self.label_EPOClass.setObjectName("label_EPOClass")
        self.gridLayout_4.addWidget(self.label_EPOClass, 1, 0, 1, 1)
        self.lineEdit_EPOClass = QtWidgets.QLineEdit(self.groupBox_EPO)
        self.lineEdit_EPOClass.setObjectName("lineEdit_EPOClass")
        self.gridLayout_4.addWidget(self.lineEdit_EPOClass, 1, 1, 1, 1)
        self.lineEdit_EPOLength = QtWidgets.QLineEdit(self.groupBox_EPO)
        self.lineEdit_EPOLength.setObjectName("lineEdit_EPOLength")
        self.gridLayout_4.addWidget(self.lineEdit_EPOLength, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_EPO, 1, 1, 1, 1)
        Subui_I2C.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Subui_I2C)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        self.menuSet = QtWidgets.QMenu(self.menubar)
        self.menuSet.setObjectName("menuSet")
        self.menuSettings = QtWidgets.QMenu(self.menuSet)
        self.menuSettings.setObjectName("menuSettings")
        Subui_I2C.setMenuBar(self.menubar)
        self.actionFonts = QtWidgets.QAction(Subui_I2C)
        self.actionFonts.setObjectName("actionFonts")
        self.actionQuit = QtWidgets.QAction(Subui_I2C)
        self.actionQuit.setObjectName("actionQuit")
        self.menuSettings.addAction(self.actionFonts)
        self.menuSet.addAction(self.menuSettings.menuAction())
        self.menuSet.addSeparator()
        self.menuSet.addAction(self.actionQuit)
        self.menubar.addAction(self.menuSet.menuAction())

        self.retranslateUi(Subui_I2C)
        QtCore.QMetaObject.connectSlotsByName(Subui_I2C)

    def retranslateUi(self, Subui_I2C):
        _translate = QtCore.QCoreApplication.translate
        Subui_I2C.setWindowTitle(_translate("Subui_I2C", "I2C(CH341T)"))
        self.groupBox_Device.setTitle(_translate("Subui_I2C", "Device"))
        self.label_VID.setText(_translate("Subui_I2C", "VID"))
        self.label_PID.setText(_translate("Subui_I2C", "PID"))
        self.label_Interface.setText(_translate("Subui_I2C", "Interface"))
        self.groupBox_EPI.setTitle(_translate("Subui_I2C", "Endpoint(in)"))
        self.label_EPIAddress.setText(_translate("Subui_I2C", "Address"))
        self.label_EPIClass.setText(_translate("Subui_I2C", "Class"))
        self.label_EPILength.setText(_translate("Subui_I2C", "Length"))
        self.groupBox_RS.setTitle(_translate("Subui_I2C", "Receive and Send "))
        self.label_RECIEVE.setText(_translate("Subui_I2C", "RECEIVE"))
        self.label_SEND.setText(_translate("Subui_I2C", "SEND"))
        self.label.setText(_translate("Subui_I2C", "cmd"))
        self.label_2.setText(_translate("Subui_I2C", "data"))
        self.groupBox_Operate.setTitle(_translate("Subui_I2C", "Operate"))
        self.pushButton_FindDevices.setText(_translate("Subui_I2C", "Find devices"))
        self.pushButton_ConnectDevice.setText(_translate("Subui_I2C", "Connect device"))
        self.pushButton_ReadConfig.setText(_translate("Subui_I2C", "Read config"))
        self.pushButton_SendData.setText(_translate("Subui_I2C", "Send data"))
        self.pushButton_ReceiveData.setText(_translate("Subui_I2C", "Receive data"))
        self.pushButton_Clear.setText(_translate("Subui_I2C", "Clear history"))
        self.groupBox_EPO.setTitle(_translate("Subui_I2C", "Endpoint(out)"))
        self.label_EPOLength.setText(_translate("Subui_I2C", "Length"))
        self.label_EPOAddress.setText(_translate("Subui_I2C", "Address"))
        self.label_EPOClass.setText(_translate("Subui_I2C", "Class"))
        self.menuSet.setTitle(_translate("Subui_I2C", "System"))
        self.menuSettings.setTitle(_translate("Subui_I2C", "Settings"))
        self.actionFonts.setText(_translate("Subui_I2C", "Fonts"))
        self.actionQuit.setText(_translate("Subui_I2C", "Quit"))
